version: 1.0

num_classes: 2

classes: ["background", "building"]

class_to_color:
  "background": 0
  "building": 255

imagesize: 512

train:
  batchsize: 8
  shuffle: True
validation:
  batchsize: 16
  shuffle: False
task1:
  batchsize: 8
  shuffle: False
task2:
  batchsize: 16
  shuffle: False